# -*- coding: utf-8 -*-
"""
/***************************************************************************
 data_filter
                                 A QGIS plugin
 to change data filter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-14
        copyright            : (C) 2024 by Federico Gianoli
        email                : gianoli.federico@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load data_filter class from file data_filter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .data_filter import data_filter
    return data_filter(iface)
